title: Sivaraj Sankar
logo: /assets/img/CirclePhoto.png
description: |+
            Aspiring Data Scientist/Machine Learning Engineer
            Software Developer-BFSI Domain
show_downloads: true
#theme: Minima
theme: jekyll-theme-minimal
