title: Sivaraj Sankar
logo: /assets/img/CirclePhoto.png
description: 
  - AI Engineer                 
  - ㅤㅤㅤㅤㅤㅤㅤㅤGenAI Software Developer - BFSI Financial Domain
#show_downloads: true
#theme: Minima
theme: jekyll-theme-minimal
